#pragma once
// コアコンポーネント
#include "TransformComponent.h"
#include "ObjectInfoComponent.h"
#include "VertexComponent.h"
#include "MaterialComponent.h"
#include "ModelRenderComponent.h"
#include "ScriptComponent.h"
#include "CameraComponent.h"
#include "SphereColliderComponent.h"
// シューティング用のコンポーネント
#include "shooting/ShootingPlayerComponent.h"
