-- Generated by QuickForgeEngine ProjectGenerator.
local _sourceDirectory = path.getabsolute(path.getdirectory(_SCRIPT))

project "Launcher"
    location (_sourceDirectory)
    language "C++"
    objdir (path.join(QFE_PROJECT_ROOT, "../generated/obj/%{prj.name}/%{cfg.buildcfg}/%{cfg.platform}"))
    targetdir (path.join(QFE_PROJECT_ROOT, "../generated/outputs/%{cfg.buildcfg}/%{cfg.platform}"))
    files {
        path.join(_sourceDirectory, "**.h"),
        path.join(_sourceDirectory, "**.hpp"),
        path.join(_sourceDirectory, "**.c"),
        path.join(_sourceDirectory, "**.cpp"),
    }
    architecture ("x64")
    cppdialect ("C++20")
    staticruntime "on"
    filter "configurations:Debug"
        runtime ("Debug")
    filter "configurations:Development"
        runtime ("Release")
    filter "configurations:Release"
        runtime ("Release")
    filter {}
    filter "configurations:Debug"
        optimize ("Off")
    filter "configurations:Development"
        optimize ("Off")
    filter "configurations:Release"
        optimize ("On")
    filter {}
    filter "configurations:Debug"
        symbols ("On")
    filter "configurations:Development"
        symbols ("On")
    filter "configurations:Release"
        symbols ("Off")
    filter {}
    debugdir (path.join(QFE_PROJECT_ROOT, "."))
    multiprocessorcompile "On"
    buildoptions {
        "/utf-8",
    }
    includedirs {
        path.join(QFE_PROJECT_ROOT, "engine"),
        path.join(QFE_PROJECT_ROOT, "engine/core"),
        path.join(QFE_PROJECT_ROOT, "externals"),
        path.join(QFE_PROJECT_ROOT, "externals/imgui"),
        path.join(QFE_PROJECT_ROOT, "externals/assimp"),
        path.join(QFE_PROJECT_ROOT, "externals/assimp/include"),
        path.join(QFE_PROJECT_ROOT, "externals/imgui/imgui-node-editor-0.9.3"),
    }
    filter "configurations:Debug"
        defines {
            "_DEBUG",
            "QFE_OPTIMIZE_OFF",
            "QFE_MODE_DEBUG",
            "USE_IMGUI",
        }
    filter "configurations:Development"
        defines {
            "NDEBUG",
            "QFE_OPTIMIZE_OFF",
            "QFE_MODE_DEVELOPMENT",
            "USE_IMGUI",
        }
    filter "configurations:Release"
        defines {
            "NDEBUG",
            "QFE_OPTIMIZE_ON",
            "QFE_MODE_RELEASE",
            "NO_IMGUI",
        }
    filter {}
    kind "WindowedApp"
    includedirs {
        path.join(QFE_PROJECT_ROOT, "engine"),
        path.join(QFE_PROJECT_ROOT, "engine/core"),
        path.join(QFE_PROJECT_ROOT, "externals"),
        path.join(QFE_PROJECT_ROOT, "externals/assimp"),
        path.join(QFE_PROJECT_ROOT, "externals/assimp/include"),
        path.join(QFE_PROJECT_ROOT, "externals/imgui"),
    }
    links {
        "GUIEngine",
        "EngineCore",
        "ImGui",
        "WindowingSystem",
        "GraphicEngine",
        "DirectXTex",
        "Camera",
        "EngineAssetsFactory",
        "Scene",
    }
    filter "configurations:Debug"
        links {
            "assimp-vc143-mtd",
            "zlibstaticd",
        }
    filter "configurations:Development"
        links {
            "assimp-vc143-mt",
            "zlibstatic",
        }
    filter "configurations:Release"
        links {
            "assimp-vc143-mt",
            "zlibstatic",
        }
    filter {}
    filter "configurations:Debug"
        libdirs {
            "C:/Users/yutam/source/repos/QuickForgeEngine/generated/assimp/lib/Debug",
            "C:/Users/yutam/source/repos/QuickForgeEngine/generated/assimp/contrib/zlib/Debug",
        }
    filter "configurations:Development"
        libdirs {
            "C:/Users/yutam/source/repos/QuickForgeEngine/generated/assimp/lib/Release",
            "C:/Users/yutam/source/repos/QuickForgeEngine/generated/assimp/contrib/zlib/Release",
        }
    filter "configurations:Release"
        libdirs {
            "C:/Users/yutam/source/repos/QuickForgeEngine/generated/assimp/lib/Release",
            "C:/Users/yutam/source/repos/QuickForgeEngine/generated/assimp/contrib/zlib/Release",
        }
    filter {}

