---@meta

-- This file is auto-generated to provide IntelliSense for the QuickForgeEngine Lua API.
-- Do not edit this file manually.

--
--[ GLOBAL VARIABLES ]
--

---@type Transform
transform = {}

---@type Force
force = {}

---@type AABBColliderData
aabbCollider = {}

---@type SphereColliderData
sphereCollider = {}


--
--[ GLOBAL FUNCTIONS ]

---@param message string
function DebugLog(message) end

---@param functionName string
function RunAllFunction(functionName) end

---@param tagName string
---@return number
function CountEntityTag(tagName) end

--- Gets the delta time of the last frame.
---@return number
function GetDeltaTime() end

--- Gets an entity by its name.
---@param entityName string
---@return number
function GetEntity(entityName) end

--- Gets an entity by its unique ID.
---@param uniqeId number
---@return userdata
function GetEntityFromUniqeID(uniqeId) end

--- Gets the draw state of an entity's sprite.
---@param entityId number
---@return boolean
function GetIsDraw(entityId) end

--- Sets the draw state of an entity's sprite.
---@param entityId number
---@param isDraw boolean
function SetIsDraw(entityId, isDraw) end

--- Gets the Transform component of an entity.
---@param entityId number
---@return Transform
function GetTransform(entityId) end

--- Sets the translation of an entity's Transform component.
---@param entityId number
---@param translate Vector3
function SetTranslate(entityId, translate) end

--- Sets the rotation of an entity's Transform component.
---@param entityId number
---@param rotate Vector3
function SetRotate(entityId, rotate) end

--- Sets the scale of an entity's Transform component.
---@param entityId number
---@param scale Vector3
function SetScale(entityId, scale) end

--- Gets the SceneObjectData component of an entity.
---@param entityId number
---@return SceneObjectData
function GetSceneObjectData(entityId) end

--- Gets the Force component of an entity.
---@param entityId number
---@return Force
function GetForce(entityId) end

--- Gets the Material component of an entity.
---@param entityId number
---@return Material
function GetMaterial(entityId) end

--- Gets the isTrigger property from an entity's collider.
---@param entityId number
---@return boolean
function GetColliderIsTrigger(entityId) end

--- Sets the isTrigger property on an entity's collider.
---@param entityId number
---@param isTrigger boolean
function SetColliderIsTrigger(entityId, isTrigger) end

--- Creates a new entity.
---@param entityName string
---@param transform Transform
---@return number # The ID of the created entity.
function CreateEntity(entityName, transform) end

--- Creates a new entity with default transform.
---@param entityName string
---@return number # The ID of the created entity.
function SimpleCreateEntity(entityName) end

--- Loads a scene.
---@param sceneName string
function LoadScene(sceneName) end

--- Changes the model of an entity.
---@param id number # Entity ID
---@param modelName string
function ChangeModel(id, modelName) end

--- Changes the mesh of an entity.
---@param id number # Entity ID
---@param meshName string
function ChangeMesh(id, meshName) end

--- Destroys the current entity.
function destroy() end

--- Destroys the current entity.
function delete() end

--- Gets the ID of the current entity.
---@return number
function GetThisEntityId() end

--- Runs a script function on another entity.
---@param entityId number
---@param scriptName string
---@param functionName string
function RunEntityScriptFunction(entityId, scriptName, functionName) end

--- Gets a global variable from another entity's script.
---@param entityId number
---@param scriptName string
---@param varName string
---@return any
function GetEntityScriptGlobal(entityId, scriptName, varName) end

--- Sets a global variable in another entity's script.
---@param entityId number
---@param scriptName string
---@param varName string
---@param value any
function SetEntityScriptGlobal(entityId, scriptName, varName, value) end


--
--[ CLASSES ]
--

---@class SceneObjectData
---@field name string
---@field tag string
---@type SceneObjectData
SceneObjectData = {}
---@return SceneObjectData
function SceneObjectData.new() end

---@class Vector2
---@field x number
---@field y number
---@type Vector2
Vector2 = {}
---@param x number|nil
---@param y number|nil
---@return Vector2
function Vector2.new(x, y) end
---@return number
function Vector2:Length() end
---@return Vector2
function Vector2:Normalize() end

---@class Vector3
---@field x number
---@field y number
---@field z number
---@type Vector3
Vector3 = {}
---@param x number|nil
---@param y number|nil
---@param z number|nil
---@return Vector3
function Vector3.new(x, y, z) end
---@return number
function Vector3:Length() end
---@return Vector3
function Vector3:Normalize() end
---@param other Vector3
---@return number
function Vector3:Dot(other) end
---@param other Vector3
---@return Vector3
function Vector3:Cross(other) end

---@class Vector4
---@field x number
---@field y number
---@field z number
---@field w number
---@type Vector4
Vector4 = {}
---@param x number|nil
---@param y number|nil
---@param z number|nil
---@param w number|nil
---@return Vector4
function Vector4.new(x, y, z, w) end
---@return number
function Vector4:Length() end
---@return Vector4
function Vector4:Normalize() end

---@class Transform
---@field scale Vector3
---@field rotate Vector3
---@field translate Vector3
---@type Transform
Transform = {}
---@return Transform
function Transform.new() end
---@param speed number
function Transform:AddForward(speed) end
---@param speed number
function Transform:AddRight(speed) end

---@class Sphere
---@field center Vector3
---@field radius number
---@type Sphere
Sphere = {}
---@return Sphere
function Sphere.new() end

---@class AABB
---@field min Vector3
---@field max Vector3
---@type AABB
AABB = {}
---@return AABB
function AABB.new() end

---@class AABBColliderData
---@field aabb AABB
---@field isHit boolean
---@field isTrigger boolean
---@field isStatic boolean
---@field colliderLayer number
---@field eventColliderLayer number
---@type AABBColliderData
AABBColliderData = {}
---@return AABBColliderData
function AABBColliderData.new() end

---@class SphereColliderData
---@field sphere Sphere
---@field isHit boolean
---@field isTrigger boolean
---@field isStatic boolean
---@field colliderLayer number
---@field eventColliderLayer number
---@type SphereColliderData
SphereColliderData = {}
---@return SphereColliderData
function SphereColliderData.new() end

---@class Force
---@field velocity Vector3
---@field acceleration Vector3
---@field mass number
---@field friction number
---@field gravityStrength number
---@field isGravity boolean
---@type Force
Force = {}
---@return Force
function Force.new() end

---@class Material
---@field color Vector4
---@field enableLighting boolean
---@field uvTransform Transform
---@type Material
Material = {}
---@return Material
function Material.new() end

--
--[ this NAMESPACE ]
--

---@class this
---@type this
this = {}

---@return number
function this.GetEntityId() end

--
--[ QFE NAMESPACE ]
--

---@class QFE
---@field Input QFE.Input
---@field Audio QFE.Audio
---@field Math QFE.Math
---@type QFE
QFE = {}

---@class QFE.Input
---@return Vector2
function QFE.Input.GetKeyMoveDir() end
---@param actionName string
---@return boolean
function QFE.Input.GetKeyPress(actionName) end
---@param actionName string
---@return boolean
function QFE.Input.GetKeyTrigger(actionName) end
---@param actionName string
---@return boolean
function QFE.Input.GetKeyRelease(actionName) end
---@param button number # 0 for Left, 1 for Right, 2 for Middle
---@return boolean
function QFE.Input.GetMousePress(button) end
---@param button number # 0 for Left, 1 for Right, 2 for Middle
---@return boolean
function QFE.Input.GetMouseTrigger(button) end
---@param button number # 0 for Left, 1 for Right, 2 for Middle
---@return boolean
function QFE.Input.GetMouseRelease(button) end
---@return Vector2
function QFE.Input.GetMouseScreenPos() end
---@return Vector2
function QFE.Input.GetMouseMoveDir() end
---@return number
function QFE.Input.GetMouseWheelDir() end
---@param button number # Gamepad button code
---@return boolean
function QFE.Input.GetGamePadPress(button) end
---@param button number # Gamepad button code
---@return boolean
function QFE.Input.GetGamePadTrigger(button) end
---@param button number # Gamepad button code
---@return boolean
function QFE.Input.GetGamePadRelease(button) end
---@return Vector2
function QFE.Input.GetGamePadLeftStickDir() end
---@return Vector2
function QFE.Input.GetGamePadRightStickDir() end

---@class QFE.Audio
---@param soundName string
---@return number # Audio handle
function QFE.Audio.LoadSound(soundName) end
---@param soundHandle number
---@param isLoop boolean
---@param volume number
---@return number # Play handle
function QFE.Audio.PlaySound(soundHandle, isLoop, volume) end
---@param playHandle number
function QFE.Audio.StopSound(playHandle) end

---@class QFE.Math
---@field pi number
---@param from number
---@param to number
---@param speed number
---@return number
function QFE.Math.SimpleEaseIn(from, to, speed) end
---@param a number
---@param b number
---@param t number
---@return number
function QFE.Math.Leap(a, b, t) end
---@param from number
---@param to number
---@param t number
---@return number
function QFE.Math.Slerp(from, to, t) end
---@param v1 Vector3
---@param v2 Vector3
---@param t number
---@return Vector3
function QFE.Math.Slerp(v1, v2, t) end -- Overload
---@param from number
---@param to number
---@param t number
---@return number
function QFE.Math.EaseIn(from, to, t) end
---@param from number
---@param to number
---@param t number
---@return number
function QFE.Math.EaseOut(from, to, t) end
---@param from number
---@param to number
---@param t number
---@return number
function QFE.Math.EaseInOut(from, to, t) end
---@param min number|nil # Optional min value, defaults to 0.0
---@param max number|nil # Optional max value, defaults to 1.0
---@return number
function QFE.Math.Rand(min, max) end
---@param dir Vector3
---@return Vector3
function QFE.Math.LookAtFromDir(dir) end