-- Generated by QuickForgeEngine ProjectGenerator.
local _root = path.getabsolute(path.getdirectory(_SCRIPT))
QFE_PROJECT_ROOT = _root

workspace "QuickForgeEngine"
    location (QFE_PROJECT_ROOT)
    configurations {
        "Debug",
        "Development",
        "Release",
    }
    objdir (path.join(QFE_PROJECT_ROOT, "../generated/obj/%{prj.name}/%{cfg.buildcfg}/%{cfg.platform}"))
    targetdir (path.join(QFE_PROJECT_ROOT, "../generated/outputs/%{cfg.buildcfg}/%{cfg.platform}"))
    architecture ("x64")
    cppdialect ("C++20")
    staticruntime "on"
    filter "configurations:Debug"
        runtime ("Debug")
    filter "configurations:Development"
        runtime ("Release")
    filter "configurations:Release"
        runtime ("Release")
    filter {}
    filter "configurations:Debug"
        optimize ("Off")
    filter "configurations:Development"
        optimize ("Off")
    filter "configurations:Release"
        optimize ("On")
    filter {}
    filter "configurations:Debug"
        symbols ("On")
    filter "configurations:Development"
        symbols ("On")
    filter "configurations:Release"
        symbols ("Off")
    filter {}
    debugdir (path.join(QFE_PROJECT_ROOT, "."))
    multiprocessorcompile "On"
    buildoptions {
        "/utf-8",
    }
    includedirs {
        path.join(QFE_PROJECT_ROOT, "engine"),
        path.join(QFE_PROJECT_ROOT, "engine/core"),
        path.join(QFE_PROJECT_ROOT, "externals"),
        path.join(QFE_PROJECT_ROOT, "externals/imgui"),
        path.join(QFE_PROJECT_ROOT, "externals/assimp"),
        path.join(QFE_PROJECT_ROOT, "externals/assimp/include"),
        path.join(QFE_PROJECT_ROOT, "externals/imgui/imgui-node-editor-0.9.3"),
    }
    filter "configurations:Debug"
        defines {
            "_DEBUG",
            "QFE_OPTIMIZE_OFF",
            "QFE_MODE_DEBUG",
            "USE_IMGUI",
        }
    filter "configurations:Development"
        defines {
            "NDEBUG",
            "QFE_OPTIMIZE_OFF",
            "QFE_MODE_DEVELOPMENT",
            "USE_IMGUI",
        }
    filter "configurations:Release"
        defines {
            "NDEBUG",
            "QFE_OPTIMIZE_ON",
            "QFE_MODE_RELEASE",
            "NO_IMGUI",
        }
    filter {}

group "External"
dofile(path.join(_root, "externals/premake.lua"))
dofile(path.join(_root, "externals/imgui/premake.lua"))
dofile(path.join(_root, "externals/DirectXTex/premake.lua"))
dofile(path.join(_root, "externals/assimp/premake.lua"))
group ""

group "00_System"
dofile(path.join(_root, "engine/resources/premake.lua"))
dofile(path.join(_root, "engine/core/premake.lua"))
group ""

group "01_SubSystems"
dofile(path.join(_root, "engine/window/premake.lua"))
dofile(path.join(_root, "engine/graphics/premake.lua"))
dofile(path.join(_root, "engine/gui/premake.lua"))
dofile(path.join(_root, "engine/input/premake.lua"))
dofile(path.join(_root, "engine/physics/premake.lua"))
group ""

group "02_Middleware"
dofile(path.join(_root, "engine/assetfactory/premake.lua"))
dofile(path.join(_root, "engine/camera/premake.lua"))
dofile(path.join(_root, "engine/scene/premake.lua"))
dofile(path.join(_root, "engine/components/premake.lua"))
group ""

group "03_Frameworks"
dofile(path.join(_root, "engine/framework/application/premake.lua"))
dofile(path.join(_root, "engine/framework/graphic/premake.lua"))
dofile(path.join(_root, "engine/framework/window/premake.lua"))
dofile(path.join(_root, "engine/framework/gui/premake.lua"))
dofile(path.join(_root, "engine/framework/input/premake.lua"))
dofile(path.join(_root, "engine/framework/physics/premake.lua"))
dofile(path.join(_root, "engine/framework/scene/premake.lua"))
dofile(path.join(_root, "engine/framework/assets/premake.lua"))
group ""

group "04_Applications"
dofile(path.join(_root, "editor/premake.lua"))
dofile(path.join(_root, "sandbox/premake.lua"))
dofile(path.join(_root, "runtime/premake.lua"))
dofile(path.join(_root, "launcher/premake.lua"))
group ""

group "Tools"
dofile(path.join(_root, "tools/project-generator/premake.lua"))
group ""

