name: Release

on:
  push:
    branches:
      - master

jobs:
  release:
    name: Generate Release Notes
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run Semantic Release
        uses: cycjimmy/semantic-release-action@v4
        with:
          # 解析用のプラグイン（これだけは追加ダウンロードが必要なので残します）
          extra_plugins: |
            @semantic-release/commit-analyzer
            @semantic-release/release-notes-generator
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
